import type { HotkeyConfig } from '../../shared/types'

export const VOICE_KEY_MANAGED_BLOCK_START = '-- >>> Voice Key managed integration >>>'
export const VOICE_KEY_MANAGED_BLOCK_END = '-- <<< Voice Key managed integration <<<'

type HyprlandAccelerator = {
  binding: string
  releaseBinding: string
}

const MODIFIER_ALIASES: Record<string, string> = {
  alt: 'ALT',
  option: 'ALT',
  control: 'CTRL',
  ctrl: 'CTRL',
  command: 'SUPER',
  cmd: 'SUPER',
  meta: 'SUPER',
  super: 'SUPER',
  commandorcontrol: 'CTRL',
  cmdorctrl: 'CTRL',
  shift: 'SHIFT',
}

const KEY_ALIASES: Record<string, string> = {
  ' ': 'SPACE',
  space: 'SPACE',
  enter: 'RETURN',
  return: 'RETURN',
  tab: 'TAB',
  backspace: 'BACKSPACE',
  delete: 'DELETE',
  escape: 'ESCAPE',
  esc: 'ESCAPE',
  up: 'UP',
  down: 'DOWN',
  left: 'LEFT',
  right: 'RIGHT',
  home: 'HOME',
  end: 'END',
  pageup: 'PAGEUP',
  pagedown: 'PAGEDOWN',
  insert: 'INSERT',
  comma: 'comma',
  ',': 'comma',
  period: 'period',
  '.': 'period',
  slash: 'slash',
  '/': 'slash',
  backslash: 'backslash',
  '\\': 'backslash',
  semicolon: 'semicolon',
  ';': 'semicolon',
  quote: 'apostrophe',
  "'": 'apostrophe',
  bracketleft: 'bracketleft',
  '[': 'bracketleft',
  bracketright: 'bracketright',
  ']': 'bracketright',
  minus: 'minus',
  '-': 'minus',
  equal: 'equal',
  '=': 'equal',
  backquote: 'grave',
  '`': 'grave',
}

function normalizeKey(value: string): string | null {
  const trimmed = value.trim()
  const lower = trimmed.toLowerCase()
  const modifier = MODIFIER_ALIASES[lower]
  if (modifier) return `${modifier}_L`
  if (KEY_ALIASES[lower]) return KEY_ALIASES[lower]
  if (/^[a-z0-9]$/iu.test(trimmed)) return trimmed.toUpperCase()
  if (/^f(?:[1-9]|1\d|2[0-4])$/iu.test(trimmed)) return trimmed.toUpperCase()
  return null
}

export function acceleratorToHyprland(accelerator: string): HyprlandAccelerator | null {
  const parts = accelerator
    .split('+')
    .map((part) => part.trim())
    .filter(Boolean)
  const rawKey = parts.pop()
  if (!rawKey) return null

  const modifiers: string[] = []
  for (const rawModifier of parts) {
    const modifier = MODIFIER_ALIASES[rawModifier.toLowerCase()]
    if (!modifier || modifiers.includes(modifier)) return null
    modifiers.push(modifier)
  }

  const key = normalizeKey(rawKey)
  if (!key) return null

  const binding = [...modifiers, key].join(' + ')
  return {
    binding,
    releaseBinding: key,
  }
}

function luaString(value: string): string {
  return JSON.stringify(value)
}

function renderBinding(
  accelerator: string,
  event: string,
  description: string,
  flags?: string[],
): string {
  const parsed = acceleratorToHyprland(accelerator)
  if (!parsed) {
    throw new Error(`Unsupported Hyprland accelerator: ${accelerator}`)
  }

  const options = [`description = ${luaString(description)}`, ...(flags ?? [])].join(', ')
  return `hl.bind(${luaString(parsed.binding)}, hl.dsp.event(${luaString(event)}), { ${options} })`
}

export function buildHyprlandManagedBlock(
  hotkeys: HotkeyConfig,
  translationEnabled: boolean,
): string {
  const ptt = acceleratorToHyprland(hotkeys.pttKey)
  if (!ptt) {
    throw new Error(`Unsupported Hyprland accelerator: ${hotkeys.pttKey}`)
  }

  const lines = [
    VOICE_KEY_MANAGED_BLOCK_START,
    '-- Generated by Voice Key. Use Settings > Linux integration to update or remove it.',
    'hl.window_rule({ name = "voice-key-overlay", match = { class = "voice-key", title = "Voice Key Overlay" }, float = true, pin = true, no_initial_focus = true })',
    renderBinding(hotkeys.pttKey, 'voice-key:ptt-start', 'Voice Key push-to-talk', [
      'non_consuming = true',
      'transparent = true',
    ]),
    `hl.bind(${luaString(ptt.releaseBinding)}, hl.dsp.event("voice-key:ptt-stop"), { description = "Voice Key push-to-talk release", release = true, ignore_mods = true, non_consuming = true, transparent = true, submap_universal = true })`,
    renderBinding(hotkeys.toggleSettings, 'voice-key:open-settings', 'Voice Key settings'),
  ]

  if (translationEnabled && hotkeys.translateKey) {
    lines.push(
      renderBinding(hotkeys.translateKey, 'voice-key:translate', 'Voice Key translate selection'),
    )
  }

  lines.push(VOICE_KEY_MANAGED_BLOCK_END)
  return `${lines.join('\n')}\n`
}

export function findHyprlandManagedBlock(source: string): string | null {
  const start = source.indexOf(VOICE_KEY_MANAGED_BLOCK_START)
  if (start < 0) return null
  const endMarker = source.indexOf(VOICE_KEY_MANAGED_BLOCK_END, start)
  if (endMarker < 0) return null
  const end = endMarker + VOICE_KEY_MANAGED_BLOCK_END.length
  return `${source.slice(start, end).trimEnd()}\n`
}

export function hasMalformedHyprlandManagedBlock(source: string): boolean {
  const startCount = source.split(VOICE_KEY_MANAGED_BLOCK_START).length - 1
  const endCount = source.split(VOICE_KEY_MANAGED_BLOCK_END).length - 1
  return startCount !== endCount || startCount > 1
}

export function upsertHyprlandManagedBlock(source: string, managedBlock: string): string {
  if (hasMalformedHyprlandManagedBlock(source)) {
    throw new Error('The existing Voice Key managed block is incomplete or duplicated')
  }
  const existing = findHyprlandManagedBlock(source)
  const normalizedBlock = managedBlock.trimEnd()
  if (!existing) {
    const prefix = source.trimEnd()
    return `${prefix ? `${prefix}\n\n` : ''}${normalizedBlock}\n`
  }

  return `${source.replace(existing.trimEnd(), normalizedBlock).trimEnd()}\n`
}

export function removeHyprlandManagedBlock(source: string): string {
  if (hasMalformedHyprlandManagedBlock(source)) {
    throw new Error('The existing Voice Key managed block is incomplete or duplicated')
  }
  const existing = findHyprlandManagedBlock(source)
  if (!existing) return source

  const withoutBlock = source.replace(existing.trimEnd(), '')
  return `${withoutBlock.replace(/\n{3,}/gu, '\n\n').trimEnd()}${withoutBlock.trim() ? '\n' : ''}`
}
